### ISSUE TITLE
How did you reverse the parameters for the auth ticket?

### ISSUE THREAD

**Issue by Thordin** [jesterret/SteamUserAuthToken#1]
Just wondering how you reversed the parameters here as the timestamp doesn't seem to be correct. I made it actually be the "ms since connected to steam" and then it stopped working after about a day. I'd also be interested in CancelAuthTicket.

https://github.com/jesterret/SteamUserAuthToken/blob/master/src/SteamUserAuthToken/SteamAuthTicket.cs#L57

**Comment by jesterret** [comment]
Hi, first of all, thanks for interest.
To be honest, since all those parameters are completely optional and not verified by steam for correctness,, I didn't spend too much time figuring them out.
I based my implementation on multiple sources, among them [1](https://github.com/SteamRE/SteamKit/blob/master/Resources/Structs/steam3_appticket.hsl#L20) [2](https://github.com/DoctorMcKay/node-steam-user/blob/master/components/appauth.js#L84), all using difference between server time and local time. 
Your question made me look for some more information, and I've looked into decompiled code (found version with more reversed names someone uploaded [here](https://github.com/emily33901/Argon/blob/master/reverse/CUser/GetAuthSessionTicket.cc#L65)) and what they actually put there is Plat_MSTime(), which is just QueryPerformanceFrequency call (on windows obv, just anything that get's timestamp, so `Stopwatch.GetTimestamp()` should pass), and since it's only sending lower part, it might as well be returning random values.
Also, from my testing the localip is sometimes included, but I cba to dig for hours for the conditions of something that's optional.
Notable difference from the code linked is now they send hash of the ip instead of actual ip, hashing code below, seems to be based on murmurhash.

Call to CancelAuthTicket, is basically the same as [SendTickets](https://github.com/jesterret/SteamUserAuthToken/blob/master/src/SteamUserAuthToken/SteamAuthTicket.cs#L141), but with the ticket in question removed, so I'll try to get it done soon, at the moment I'm busy with other project for a while.

    uint HashAddress(IPAddress address)
    {
        var ipBytes = address.GetAddressBytes().Reverse().ToArray();
        var ipValue = BitConverter.ToUInt32(ipBytes, 0);
        var temp = 0x85EBCA6B * (ipValue ^ (ipValue >> 16));
        var value = 0xC2B2AE35 * (temp  ^ (temp >> 13));
        return value ^ (value >> 16);
    }

**Comment by jesterret** [comment]
I believe it won't be relevant for You by now, but it's all implemented, and up on nuget.
